# `numpy`

These problems go along with the material presented in the <a href="../lectures/Basic numpy.ipynb">Basic numpy</a> notebook.

## Basic Problems

1. Import `numpy` and check your version.

In [1]:
## 1. ANSWER
import numpy as np

print(np.__version__)


1.24.2


2. Create an array from $-10$ to $10$ with steps of $1$ using `np.arange`. Hint: If you don't know how `np.arange` works search for it on the web.

In [2]:
## 2. ANSWER

## arange docs, https://numpy.org/doc/stable/reference/generated/numpy.arange.html
np.arange(-10,11,1)




array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10])

3. Create an array from $-10$ to $10$ with $1000$ evenly spaced steps using `np.linspace`.

In [3]:
## 3. ANSWER

## linspace docs, https://numpy.org/doc/stable/reference/generated/numpy.linspace.html

np.linspace(-10,10,1000)


array([-10.        ,  -9.97997998,  -9.95995996,  -9.93993994,
        -9.91991992,  -9.8998999 ,  -9.87987988,  -9.85985986,
        -9.83983984,  -9.81981982,  -9.7997998 ,  -9.77977978,
        -9.75975976,  -9.73973974,  -9.71971972,  -9.6996997 ,
        -9.67967968,  -9.65965966,  -9.63963964,  -9.61961962,
        -9.5995996 ,  -9.57957958,  -9.55955956,  -9.53953954,
        -9.51951952,  -9.4994995 ,  -9.47947948,  -9.45945946,
        -9.43943944,  -9.41941942,  -9.3993994 ,  -9.37937938,
        -9.35935936,  -9.33933934,  -9.31931932,  -9.2992993 ,
        -9.27927928,  -9.25925926,  -9.23923924,  -9.21921922,
        -9.1991992 ,  -9.17917918,  -9.15915916,  -9.13913914,
        -9.11911912,  -9.0990991 ,  -9.07907908,  -9.05905906,
        -9.03903904,  -9.01901902,  -8.998999  ,  -8.97897898,
        -8.95895896,  -8.93893894,  -8.91891892,  -8.8988989 ,
        -8.87887888,  -8.85885886,  -8.83883884,  -8.81881882,
        -8.7987988 ,  -8.77877878,  -8.75875876,  -8.73

4. Use `numpy`'s `random` subpackage (accessed using `np.random`) to generate a random draw from $[0,1]$.

In [4]:
## 4. ANSWER

## docs, https://numpy.org/doc/stable/reference/random/generated/numpy.random.random.html
np.random.random()



0.11603439222484868

5. Use `numpy`'s `random` to make a random array of length 20 and store it in a variable called `x`.  Run `x > .2`, what comes out? Then try `x[x >.2]`, what happens?

In [5]:
## 5. ANSWER
## Note you don't need to print out the results, I 
## just did that so I'd only need one code chunk

## make the array
x = np.random.random(20)
print(x)
print()

## check where x > .2
print(x > .2)
print()

## get the values of x where x > .2
print(x[x > .2])



[0.82945132 0.26933866 0.34740473 0.38943633 0.13958581 0.59382039
 0.79602535 0.57818561 0.9327706  0.10524205 0.3747918  0.51567678
 0.58941443 0.13729558 0.42287576 0.68723485 0.1523173  0.11779451
 0.53970089 0.67814932]

[ True  True  True  True False  True  True  True  True False  True  True
  True False  True  True False False  True  True]

[0.82945132 0.26933866 0.34740473 0.38943633 0.59382039 0.79602535
 0.57818561 0.9327706  0.3747918  0.51567678 0.58941443 0.42287576
 0.68723485 0.53970089 0.67814932]


## More Advanced Problems

1. Rewrite your answer to <i>More Advanced Problems 1.</i> in <a href="Writing to File and Importing a Package.ipynb">Writing to File and Importing a Package</a>, no need to write the result to file this time.

In [6]:
## 1. ANSWER

### MAKING THE FLIPS ###
# This is the same as a coin flip
# Tails would be a 0 and 1 would be a Heads
print(np.random.binomial(1, p=.5))
print()

# We can get 100 flips like so
print(np.random.binomial(1, p=.5, size=100))
print()


# flip the coin 100 times
flips = np.random.binomial(1, p=.5, size=100)

# We can map 0,1 to -1,1 using y=2x-1
flips = 2*flips - 1
print(flips)
print()

### GETTING THE POSITONS ###

# initialize the positions array
pos = np.zeros(101)

# use cumsum to get the walk
pos[1:] = np.cumsum(flips)

print(pos)

1

[1 0 1 0 0 1 1 0 1 0 0 1 0 1 1 0 0 0 1 0 1 1 1 0 1 1 1 0 0 1 0 0 1 1 0 1 0
 1 1 1 1 1 0 1 1 1 0 1 0 0 1 0 1 1 1 1 0 1 0 0 1 0 0 1 1 1 1 0 0 0 1 1 0 0
 0 0 0 0 0 0 1 1 1 0 1 0 1 1 0 0 1 1 1 0 1 1 1 1 1 0]

[ 1 -1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1  1  1 -1  1 -1 -1 -1 -1 -1  1
  1 -1  1  1 -1  1  1 -1 -1 -1  1 -1  1  1  1 -1  1  1 -1 -1 -1 -1  1  1
 -1 -1 -1 -1  1 -1 -1 -1  1 -1 -1 -1  1 -1 -1  1 -1  1  1  1 -1  1  1 -1
 -1  1  1 -1  1 -1  1 -1 -1 -1  1 -1  1 -1  1  1 -1 -1  1 -1 -1  1  1 -1
 -1 -1 -1 -1]

[  0.   1.   0.  -1.  -2.  -3.  -4.  -3.  -2.  -1.   0.  -1.  -2.  -3.
  -4.  -3.  -2.  -3.  -2.  -3.  -4.  -5.  -6.  -7.  -6.  -5.  -6.  -5.
  -4.  -5.  -4.  -3.  -4.  -5.  -6.  -5.  -6.  -5.  -4.  -3.  -4.  -3.
  -2.  -3.  -4.  -5.  -6.  -5.  -4.  -5.  -6.  -7.  -8.  -7.  -8.  -9.
 -10.  -9. -10. -11. -12. -11. -12. -13. -12. -13. -12. -11. -10. -11.
 -10.  -9. -10. -11. -10.  -9. -10.  -9. -10.  -9. -10. -11. -12. -11.
 -12. -11. -12. -11. -10. -11. -12. -11. -12. -13. -12. -11

2. Write a function that produces a random walk of length $n$ using `numpy`.

In [7]:
## 2. ANSWER

# Now we just need to package the above code into a function :)
def random_walk(N):
    # get the flips
    flips = np.random.binomial(1, p=.5, size=N)
    flips = 2*flips - 1

    # Get the positions
    pos = np.zeros(N+1)
    pos[1:] = np.cumsum(flips)
    
    # return the positions
    return pos

In [8]:
# let's print some short walks
for i in range(10):
    print(random_walk(10))
    print()

[ 0. -1. -2. -1.  0. -1. -2. -3. -4. -3. -4.]

[ 0. -1.  0.  1.  0. -1. -2. -3. -4. -5. -6.]

[ 0. -1. -2. -3. -4. -5. -4. -5. -4. -5. -6.]

[ 0.  1.  0. -1.  0.  1.  2.  3.  4.  3.  4.]

[ 0. -1.  0.  1.  0. -1.  0. -1. -2. -1. -2.]

[ 0.  1.  0. -1.  0. -1.  0.  1.  0.  1.  2.]

[0. 1. 2. 3. 4. 3. 2. 1. 2. 1. 2.]

[ 0. -1.  0. -1. -2. -3. -2. -1. -2. -3. -2.]

[ 0.  1.  0. -1.  0. -1. -2. -1. -2. -3. -2.]

[0. 1. 2. 3. 2. 3. 2. 1. 2. 3. 4.]



--------------------------

This notebook was written for the Erd&#337;s Institute C&#337;de Data Science Boot Camp by Matthew Osborne, Ph. D., 2023.

Any potential redistributors must seek and receive permission from Matthew Tyler Osborne, Ph.D. prior to redistribution. Redistribution of the material contained in this repository is conditional on acknowledgement of Matthew Tyler Osborne, Ph.D.'s original authorship and sponsorship of the Erdős Institute as subject to the license (see License.md)